version: "3.7"
services:
  pronuncii-db:
    container_name: pronuncii-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "pronuncii-db:/var/lib/mysql"
      - "./mysql/log/:/var/log/mysql/"
      - "./mysql/conf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pronuncii
    ports:
      - "3309:3306"
volumes:
  pronuncii-db:
