version: "3.7"
services:
  pronuncii-py:
    build: .
    container_name: pronuncii-py
    volumes:
      - "./src/:/app/"
    ports:
      - "85:85"
    depends_on:
      pronuncii-db:
        condition: service_healthy

  pronuncii-db:
    container_name: pronuncii-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "pronuncii-db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pronuncii
    ports:
      - "3309:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10

  pronuncii-front:
    container_name: pronuncii-front
    build:
      dockerfile: ./Dockerfile-front
    volumes:
      - "./src/:/app/"
volumes:
  pronuncii-db:
